BUILTIN_SAMPLE_PRESET_NAMES: dict[str, str] = {
    'OCARINA:G080'           : '@sample/Ocarina:G080',
    'BANDONEON:C072'         : '@sample/Bandoneon:C072',
    'HARP:F077'              : '@sample/Harp:F077',
    'MALON & LULU VOICE:D074': '@sample/Malon & Lulu Voice:D074',
    'PICCOLO:G091'           : '@sample/Piccolo:G091',
    'PANDEIRO:TAP'           : '@sample/Pandeiro:TAP',
    'TAMBOURINE:A118'        : '@sample/Tambourine:A118',
    'TIMPANI:C048'           : '@sample/Timpani:C048',
    'PIANO:C072'             : '@sample/Piano:C072',
    'FEMALE CHOIR:B071'      : '@sample/Female Choir:B071',
    'FEMALE CHOIR:F077'      : '@sample/Female Choir:F077',
    'HARP:F065'              : '@sample/Harp:F065',
    'GLOCKENSPIEL:B083'      : '@sample/Glockenspiel:B083',
    'CONCERT BASS DRUM:D038' : '@sample/Concert Bass Drum:D038',
    'ORCH SNARE:SNGL'        : '@sample/Orch Snare:SNGL',
    'ORCH SNARE:ROLL'        : '@sample/Orch Snare:ROLL',
    'CRASH CYMBAL:C060'      : '@sample/Crash Cymbal:C060',
    'PANDEIRO:SLAP'          : '@sample/Pandeiro:SLAP',
    'TROMBONE:G067'          : '@sample/Trombone:G067',
    'PIANO:A045'             : '@sample/Piano:A045',
    'PIANO:C060'             : '@sample/Piano:C060',
    'VIOLIN:A069'            : '@sample/Violin:A069',
    'STRINGS:C036'           : '@sample/Strings:C036',
    'STRINGS:G056'           : '@sample/Strings:G056',
    'STRINGS:G068'           : '@sample/Strings:G068',
    'OBOE:E076'              : '@sample/Oboe:E076',
    'FRENCH HORN:C072'       : '@sample/French Horn:C072',
    'TRUMPET:C072'           : '@sample/Trumpet:C072',
    'TUBA:E040'              : '@sample/Tuba:E040',
    'HARMONICA:G068'         : '@sample/Harmonica:G068',
    'NYLON STR GUITAR:G056'  : '@sample/Nylon Str Guitar:G056',
    'NYLON STR GUITAR:D075'  : '@sample/Nylon Str Guitar:D075',
    'BASSOON:A045'           : '@sample/Bassoon:A045',
    'PIZZ. STRINGS:B047'     : '@sample/Pizz. Strings:B047',
    'PIZZ. STRINGS:A070'     : '@sample/Pizz. Strings:A070',
    'ACOUSTIC BASS:A033'     : '@sample/Acoustic Bass:A033',
    'SYNFANTASIA3:D075'      : '@sample/SYNFantasia3:D075',
    'EERIE WIND:F042'        : '@sample/EERIE WIND:F042',
    'SYNTH STRINGS:G067'     : '@sample/Synth Strings:G067',
    'MALE CHOIR:G067'        : '@sample/Male Choir:G067',
    'MALE CHOIR:C109'        : '@sample/Male Choir:C109',
    'BOUZOUKI:D050'          : '@sample/Bouzouki:D050',
    'BOUZOUKI:D062'          : '@sample/Bouzouki:D062',
    'DJEMBE:OPEN'            : '@sample/Djembe:OPEN',
    'DJEMBE:SLAP'            : '@sample/Djembe:SLAP',
    'DJEMBE:MUTE'            : '@sample/Djembe:MUTE',
    'GONG:G068'              : '@sample/Gong:G068',
    'BAR CHIMES:D123'        : '@sample/Bar Chimes:D123',
    'HARPSICHORD:G067'       : '@sample/Harpsichord:G067',
    'CLARINET:C072'          : '@sample/Clarinet:C072',
    'BANJO:D050'             : '@sample/Banjo:D050',
    'BANJO:A057'             : '@sample/Banjo:A057',
    'PERC:CONGA:MUTE'        : '@sample/perc:CONGA:MUTE',
    'PERC:CONGA:OPEN'        : '@sample/perc:CONGA:OPEN',
    'PERC:CONGA:SLAP'        : '@sample/perc:CONGA:SLAP',
    'CABASA:D123'            : '@sample/Cabasa:D123',
    'MARIMBA:D062'           : '@sample/Marimba:D062',
    'MARIMBA:D074'           : '@sample/Marimba:D074',
    'SUSTAIN E. GUITAR:A045' : '@sample/Sustain E. Guitar:A045',
    'SUSTAIN E. GUITAR:C060' : '@sample/Sustain E. Guitar:C060',
    'SUSTAIN E. GUITAR:G079' : '@sample/Sustain E. Guitar:G079',
    'CHURCH BELL:A070'       : '@sample/Church Bell:A070',
    'STEEL DRUM:C060'        : '@sample/Steel Drum:C060',
    'STEEL DRUM:D074'        : '@sample/Steel Drum:D074',
    'DIGI PAD 04:F065'       : '@sample/DIGI PAD 04:F065',
    'BENT CONGA:C072'        : '@sample/Bent Conga:C072',
    'CUICA:OPEN'             : '@sample/Cuica:OPEN',
    'CUICA:MUTE'             : '@sample/Cuica:MUTE',
    'REVERB MARIMBA:A057'    : '@sample/Reverb Marimba:A057',

    # OOT-Exclusive Samples
    'ANCIENTS:G068'          : '@sample/ANCIENTS:G068',
    'LORE DRONE:A069'        : '@sample/Lore Drone:A069',
    'SHINE:E088'             : '@sample/Shine:E088',
    'METAL GRIND:C060'       : '@sample/Metal Grind:C060',
    'PIPE ORGAN:C048'        : '@sample/Pipe Organ:C048',
    'PIPE ORGAN:C060'        : '@sample/Pipe Organ:C060',
    'CLAP:C072'              : '@sample/Clap:C072',
    'RELIGIOUS PRAYER:D086'  : '@sample/Religious Prayer:D086',
    'RELIGIOUS PRAYER:C072'  : '@sample/Religious Prayer:C072',
    'RELIGIOUS PRAYER:F089'  : '@sample/Religious Prayer:F089',
    'FU YIN GONG:A081'       : '@sample/Fu Yin Gong:A081',
    'AL RYTHM 26:LOW'        : '@sample/AL RYTHM 26:LOW',
    'AL RYTHM 26:PRIM'       : '@sample/AL RYTHM 26:PRIM',
    'BAMBREMORO:B071'        : '@sample/Bambremoro:B071',
    'AFRIK FLUTE7:LOW'       : '@sample/AFRIK FLUTE7:LOW',
    'AFRIK FLUTE7:PRIM'      : '@sample/AFRIK FLUTE7:PRIM',
    'AFRIK FLUTE7:HIGH'      : '@sample/AFRIK FLUTE7:HIGH',
    'ENIGMATIC:F054'         : '@sample/ENIGMATIC:F054',
    'TRIP-HOPPIN:KICK'       : '@sample/TRIP-HOPPIN:KICK',
    'TRIP-HOPPIN:SNRE'       : '@sample/TRIP-HOPPIN:SNRE',
    'CRUNCH ROAR:C060'       : '@sample/CRUNCH ROAR:C060',
    'DUDUK:D086'             : '@sample/Duduk:D086',

    # MM_Exclusive Samples
    'SURDO:A045'             : '@sample/Surdo:A045',
    'RAWHIDE DRUM:B047'      : '@sample/Rawhide Drum:B047',
    'STEEL STR GUITAR:D050'  : '@sample/Steel Str Guitar:D050',
    'MUTED TRUMPET:C060'     : '@sample/Muted Trumpet:C060',
    'JP CYMBAL:PRIM'         : '@sample/JP Cymbal:PRIM',
    'FRETLESS BASS:F041'     : '@sample/Fretless Bass:F041',
    'GORON CHILD:B071'       : '@sample/Goron Child:B071',
    "GIANTS' VOICE:C061"     : "@sample/Giant's Voice:C061",
    'SLEIGHBELL:B107'        : '@sample/Sleighbell:B107',
    'TENOR SAXOPHONE:A057'   : '@sample/Tenor Saxophone:A057',
    'TENOR SAXOPHONE:E064'   : '@sample/Tenor Saxophone:E064',
    'STEEL STR GUITAR:D074'  : '@sample/Steel Str Guitar:D074',
    'KICK DRUM:G043'         : '@sample/Kick Drum:G043',
    'SHAKER:E112'            : '@sample/Shaker:E112',
    'ACOUSTIC SNARE:SNGL'    : '@sample/Acoustic Snare:SNGL',
    'HI-HAT:OPEN'            : '@sample/Hi-Hat:OPEN',
    'RIDE CYMBAL:G116'       : '@sample/Ride Cymbal:G116',
    'RHODES E. PIANO:F054'   : '@sample/Rhodes E. Piano:F054',
    'RHODES E. PIANO:C072'   : '@sample/Rhodes E. Piano:C072',
    'OMINOUSITY:F018'        : '@sample/OMINOUSITY:F018',
    'VERBHHOD6:C120'         : '@sample/VERNHHOD6:C120',
    'PIT HIT 1:D038'         : '@sample/PIT HIT 1:D038',
    'MUTED E. GUITAR:E052'   : '@sample/Muted E. Guitar:E052',
    'DANGER:F066'            : '@sample/DANGER:F066',
    'ELECTRIC ORGAN:G068'    : '@sample/Electric Organ:G068',
    'UDU:D038'               : '@sample/Udu:D038',
    'UDU:A046'               : '@sample/Udu:A046',
    'CONGAS:OPEN'            : '@sample/CONGAS:OPEN',
    'CONGAS:MUTE'            : '@sample/CONGAS:MUTE',
    'BRUSH SNARE:C048'       : '@sample/Brush Snare:C048',
    'AWKBIRD1:D074'          : '@sample/AWKBIRD1:D074',
    'AWKBIRD2:D087'          : '@sample/AWKDBIRD2:D087',
    'AFRICAN 13 111-A:A093'  : '@sample/African 13 111-A:A093',
    'TUNNEL RAIN:F029'       : '@sample/TUNNEL RAIN:F029',
    'HEAVY METALLIC HIT:F066': '@sample/HEAVY METALLIC HIT:F066',
    'TABLA:G055'             : '@sample/Tabla:G055',
    'HIGH-Q:B119'            : '@sample/High-Q:B119',
    'MYSTIC PAD:F030'        : '@sample/Mystic Pad:F030',
    'VELOCITY MC-202:C036'   : '@sample/Velocity MC-202:C036',
    'ICELAND 1:D086'         : '@sample/ICELAND 1:D086',
    'BASSOON:A069'           : '@sample/Bassoon:A069',
    'ELVES:C096'             : '@sample/Elves:C096',
    'SHEHNAI:A057'           : '@sample/Shehnai:A057',
    'SITAR:A057'             : '@sample/Sitar:A057',
    'COWBELL:E076'           : '@sample/Cowbell:E076',
    'JP CYMBAL:LOW'          : '@sample/JP Cymbal:LOW',
    'JP CYMBAL:HIGH'         : '@sample/JP Cymbal:HIGH',
}